### ISSUE TITLE
TypeError: Cannot read property 'previousSibling' of undefined

### ISSUE THREAD

**Issue by danielduhh** [kobotoolbox/enketo-express#742]
I'm getting this error: 

```
Error occured during the loading of this form. It is recommended not to edit this record until this is resolved.
Please contact info@kobotoolbox.org with the link to this page and the error message below:
TypeError: Cannot read property 'previousSibling' of undefined
```

When loading a saved draft submission (`api/v2/survey/offline`) with MANY parent and child question.

Is there a limit on the amount of parent child questions enketo express can handle?

**Comment by MartijnR** [comment]
Thanks for the report. There is no limit. I do remember touching some code containing `previousSibling`. Which exact commit have you deployed? Could you perhaps also check if the error can be reproduced with an empty form?

**Comment by danielduhh** [comment]
I've got commit fefa6d6 deployed. Looks like its only happens when trying to load a saved draft. Submitting a blank form works great

**Comment by danielduhh** [comment]
More specific error:
`FormLogicError: Could not evaluate: /model/instance[@id="crop_type"]/root/item[crop_classification= /model/instance[1]/aimform_REDFS2019-baahedit/name_of_region/project_focus_areas_crop_classification/crop_classification ], message: Context node was not supplied.`

Maybe its a form publishing mistake? But it's weird it only throws an error when loading a saved draft

**Comment by MartijnR** [comment]
The last error looks like a known bug when repeat count is 0 or empty. That one was fixed in the latest version. Best to upgrade to the latest published version and see if that fixes everything for you. If not, please send form and add a step by step instruction on how to see the error. Thanks!

**Comment by danielduhh** [comment]
Updated to latest commit and error persists. Here is the form, as well as step by step instructions on how the error occurs

1. Question 25 - Select a classification from the Indicative crop_classification select one
2. Question 26 - Select a Crop type
3. Select + to add an additional Crop type
4. Add an additional Question 25 (Indicative crop_classification) & select another classification
5. Add one crop type (Question 26)
6. Select Save as draft checkbox, then Save as draft Button
7. Try to open saved submission in left menu & error should occur

[aimform_REDFS2019.xlsx](https://github.com/kobo
toolbox/enketo-express/files/994472/aimform_REDFS2019.xlsx)


Thanks for your help!

**Comment by MartijnR** [comment]
Excellent. Thanks a lot. I'll look at this tomorrow!

**Comment by MartijnR** [comment]
I cannot actually reproduce it, which might be good news.

Just checking: Are you sure Enketo Express was updated correctly (e.g. with `git pull && npm update --production && grunt && pm2 restart enketo`). I have the feeling you may still be using an old enketo-core dependency. Sometimes, I have had to resolve issues by removing the node_modules folder (`rm -R node_modules` and re-installing all npm dependencies with `npm install --production`).

**Comment by danielduhh** [comment]
yessir - I needed to remove and reinstall node_modules - Thank you @MartijnR !

**Comment by MartijnR** [comment]
great! Thx
