### ISSUE TITLE
draw widget not working (in Pages Mode?)

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#844]
Might be related to pages mode or something. See https://enketo-aggregate.appspot.com/www/formXml?readable=true&formId=widgets_on_pages

**Comment by pbowen-oc** [comment]
I just noticed there is an issue related to the draw widget and queries. On my one item, one page (not Pages mode) form with just a signature field, the query widget does not have a comment field for me to enter text. It seems to have the other UI elements.

**Comment by MartijnR** [comment]
Yes, I noticed that too. That was fixed yesterday if all went well.

**Comment by MartijnR** [comment]
Does not occur in Enketo Express and Enketo Core.

**Comment by pbowen-oc** [comment]
@MartijnR - This is still broken for us in Pages mode. When I try to click within the widget to draw, the border highlights and I see a saving message when I release the mouse button. But nothing appears in the widget.

**Comment by MartijnR** [comment]
Ah, that's too bad. Thanks. We should use the exact form you are using to reproduce this as there's something particular about it probably. Let's do this during the meeting.

**Comment by MartijnR** [comment]
* [ ] send email to Paul when done

**Comment by MartijnR** [comment]
It looks like it's the canvas resize issue. Resizing the window 'fixes' it. I see a canvas width and height of 0 too.
